WITH BASE AS (
    SELECT 1 AS a
    UNION ALL
    SELECT 2 AS a
)

, T AS (
    SELECT * FROM BASE
    UNION ALL
    SELECT * FROM SOURCE.SCHEMA.BASE_2
    UNION ALL
    SELECT * FROM BASE_2
)

, ANOTHER_TABLE_33 AS (
    SELECT * FROM T
    UNION ALL
    SELECT * FROM BASE
    WHERE 1=1
        AND T.A NOT IN (
        SELECT A FROM T
    )
)

, MORE_CONTENT AS (
    SELECT
        "INFORMATION" AS INFORMATION
        , "SOME" AS SOME
        , "CONTENT" AS CONTENT
    FROM ANOTHER_TABLE_33 
    WHERE 1 = 1
        AND "INFORMATION" = 'INFORMATION'
        AND "SOME" = 'SOME'
)

SELECT
    "INFORMATION" AS INFORMATION
    , "SOME" AS SOME
    , "CONTENT" AS CONTENT
FROM MORE_CONTENT
LEFT JOIN ANOTHER_TABLE_33 ON 1 = 1
    AND "INFORMATION" = 'INFORMATION'
    AND "SOME" = 'SOME'
WHERE 1 = 1
    AND "INFORMATION" = 'INFORMATION'
    AND "SOME" = 'SOME'